#!/bin/sh
set -e

: "${CATALOG_DB_NAME:=catalog_db}"
: "${CATALOG_DB_USER:=catalog_user}"
: "${CATALOG_DB_PASSWORD:=catalog_pw}"

: "${COMMERCE_DB_NAME:=commerce_db}"
: "${COMMERCE_DB_USER:=commerce_user}"
: "${COMMERCE_DB_PASSWORD:=commerce_pw}"

: "${PAYMENT_DB_NAME:=payment_db}"
: "${PAYMENT_DB_USER:=payment_user}"
: "${PAYMENT_DB_PASSWORD:=payment_pw}"

mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<SQL
CREATE DATABASE IF NOT EXISTS \`${CATALOG_DB_NAME}\`;
CREATE USER IF NOT EXISTS '${CATALOG_DB_USER}'@'%' IDENTIFIED BY '${CATALOG_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${CATALOG_DB_NAME}\`.* TO '${CATALOG_DB_USER}'@'%';

CREATE DATABASE IF NOT EXISTS \`${COMMERCE_DB_NAME}\`;
CREATE USER IF NOT EXISTS '${COMMERCE_DB_USER}'@'%' IDENTIFIED BY '${COMMERCE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${COMMERCE_DB_NAME}\`.* TO '${COMMERCE_DB_USER}'@'%';

CREATE DATABASE IF NOT EXISTS \`${PAYMENT_DB_NAME}\`;
CREATE USER IF NOT EXISTS '${PAYMENT_DB_USER}'@'%' IDENTIFIED BY '${PAYMENT_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${PAYMENT_DB_NAME}\`.* TO '${PAYMENT_DB_USER}'@'%';

FLUSH PRIVILEGES;
SQL
